name: Linux

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ninja-build \
            meson \
            xdg-utils \
            libgtkmm-4.0-dev \
            libadwaita-1-dev \
            libsdbus-c++-dev \
            libayatana-appindicator3-dev \
            blueprint-compiler

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build Rust Service
        run: cargo build --release --manifest-path service/Cargo.toml

      - name: Build C++ App
        run: |
          cd linux
          meson setup build --buildtype=release
          meson compile -C build

      - name: Assemble Package
        run: |
          mkdir -p build/linux/FireBox
          # Since Meson uses `install`, we can install into our temporary directory.
          DESTDIR=$(pwd)/build/linux/FireBox meson install -C linux/build
          
          # Manually copy the Rust service since it wasn't built by Meson
          # Ensure bin directory exists
          mkdir -p build/linux/FireBox/usr/local/bin
          cp target/release/firebox-service build/linux/FireBox/usr/local/bin/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FireBox-Linux
          path: build/linux/FireBox
