name: Windows

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        arch: [x64, ARM64]
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.arch == 'ARM64' && 'aarch64-pc-windows-msvc' || 'x86_64-pc-windows-msvc' }}

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ matrix.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build Rust Service
        run: cargo build --release --target ${{ matrix.arch == 'ARM64' && 'aarch64-pc-windows-msvc' || 'x86_64-pc-windows-msvc' }} --manifest-path service/Cargo.toml

      - name: Build C# App
        run: |
          cd windows
          dotnet publish App/App.csproj -c Release -r win-${{ matrix.arch }} --self-contained true -p:PublishSingleFile=true -o ../build/windows/FireBox
          dotnet publish Helper/Helper.csproj -c Release -r win-${{ matrix.arch }} --self-contained true -p:PublishSingleFile=true -o ../build/windows/FireBox

      - name: Assemble Package
        run: |
          cp target/${{ matrix.arch == 'ARM64' && 'aarch64-pc-windows-msvc' || 'x86_64-pc-windows-msvc' }}/release/firebox-service.exe build/windows/FireBox/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FireBox-Windows-${{ matrix.arch }}
          path: build/windows/FireBox
