name: Windows

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        arch: [x64, ARM64]
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.arch == 'ARM64' && 'aarch64-pc-windows-msvc' || 'x86_64-pc-windows-msvc' }}

      - name: Cache Rust dependencies
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ matrix.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Configure with CMake
        run: cmake -B build -A ${{ matrix.arch }}

      - name: Build with CMake
        run: cmake --build build --config Release

      - name: Create package
        run: |
          cd build
          cpack -C Release

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: FireBox-Windows-${{ matrix.arch }}
          path: build/FireBox-*.exe
